# docker-compose.yml
version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - "10001:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
